---
title: "Summary of Trounstine's Segregation and Inequality in Public Goods"
author: "Maria Burzillo"
date: "2/20/2020"
output: html_document
---

Trounstine's [*Segregation and Inequality in Public Goods*](https://onlinelibrary.wiley.com/doi/abs/10.1111/ajps.12227) attempts to explain differences in public goods provision and political polarization through a racial lens by examining the relationships between polarization, goods provision, and segregation. Trounstine measures segregation with Theil's H index, which measures the degree to which the diversity of a neighborhood differs from the diversity of the entire city. The main finding of the paper is that segregation, not simply diversity or political views, is an important determinant of both political polarization and spending on public goods. In general, segregation leads to the coincidence of racial and spatial political cleavages, which can make compromise on taxation and public spending difficult and tends to generally drive down the rate of spending on public goods. Because minorities are much more likely to live in racially segregated areas than whites, this suggests that public goods are also segregated across racial lines. 

For replication materials, please visit my github repo [here](https://github.com/mburzillo/milestone_3.git). 
